import os
import re

frontend_dir = r"c:\Users\yaadv\OneDrive\Desktop\E-Bazaar\Frontend"

def replace_main_content(filepath, replacement, page_type):
    if not os.path.exists(filepath): return
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Change body data-page
    content = re.sub(r'<body data-page=".*?">', f'<body data-page="{page_type}">', content)
    
    # Replace main catalog div
    content = re.sub(r'<!-- MAIN CATALOG -->.*<!-- /cat-page -->', replacement, content, flags=re.DOTALL)
    
    # Change title
    content = re.sub(r'<title id="page-title">.*?</title>', f'<title id="page-title">{page_type.title()} — E-Bazaar</title>', content)
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

brand_store_html = """<!-- MAIN CATALOG -->
<div class="brand-store-page">
  <div class="brand-hero" id="brand-hero">
    <div class="brand-logo-large" id="brand-logo-large"></div>
    <h1 class="brand-title" id="brand-title">Brand Name</h1>
    <p class="brand-desc">Official Store — Premium Quality & Assured Authenticity</p>
  </div>
  <div class="brand-content" style="max-width: var(--max-w); margin: 0 auto; padding: 40px var(--side-pad);">
    <!-- Sort bar -->
    <div class="sort-bar" style="display:flex; justify-content:space-between; align-items:center; margin-bottom:24px; border-bottom:1px solid var(--border); padding-bottom:16px;">
      <p class="result-count" id="result-count">Showing <strong>0 products</strong></p>
    </div>
    <!-- Product grid -->
    <div class="cat-grid" id="main-cat-grid" role="list" style="display:grid; grid-template-columns:repeat(auto-fill, minmax(240px, 1fr)); gap:24px;"></div>
  </div>
</div><!-- /cat-page -->"""

product_detail_html = """<!-- MAIN CATALOG -->
<div class="product-page" style="max-width: var(--max-w); margin: 0 auto; padding: 40px var(--side-pad);">
  <div class="product-container" id="product-container" style="display:grid; grid-template-columns: 1fr 1fr; gap:64px; align-items:start;">
    <!-- Generated by JS -->
  </div>
</div><!-- /cat-page -->"""

replace_main_content(os.path.join(frontend_dir, "brand-store.html"), brand_store_html, "brand-store")
replace_main_content(os.path.join(frontend_dir, "product-detail.html"), product_detail_html, "product-detail")

print("Pages setup successfully.")