const sequelize = require('./config/database');
const Product = require('./models/Product');

const shoeProducts = [
  // --- PREMIUM SNEAKERS & SPORTS ---
  {
    title: "Nike Air Jordan 1 Retro High OG Chicago",
    category: "shoes",
    brand: "Nike",
    price: 16995,
    originalPrice: 19995,
    discount: "15% off",
    rating: 4.9,
    reviews: 8400,
    sales: "22k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&q=80",
    description: "Full-grain premium leather construction with iconic colorway and encapsulated Air-Sole cushioning for court style."
  },
  {
    title: "Nike Air Force 1 '07 Triple White",
    category: "shoes",
    brand: "Nike",
    price: 9695,
    originalPrice: 11495,
    discount: "16% off",
    rating: 4.9,
    reviews: 14200,
    sales: "45k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80",
    description: "Crisp white leather overlays with metal lace dubrae and legendary low-cut silhouette for streetwear royalty."
  },
  {
    title: "Adidas Ultraboost 22 Running Shoes",
    category: "shoes",
    brand: "Adidas",
    price: 17999,
    originalPrice: 20999,
    discount: "14% off",
    rating: 4.8,
    reviews: 6100,
    sales: "18k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80",
    description: "Engineered with tailored BOOST midsole return and 360-degree fit upper for maximum long-distance marathon comfort."
  },
  {
    title: "Puma RS-X Reinvent Chunky Sneakers",
    category: "shoes",
    brand: "Puma",
    price: 8999,
    originalPrice: 10999,
    discount: "18% off",
    rating: 4.7,
    reviews: 3800,
    sales: "12k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&q=80",
    description: "Bold chunky retro silhouette layered with breathable mesh and suede panels over Running System technology."
  },
  {
    title: "New Balance 550 Vintage White Green Sneakers",
    category: "shoes",
    brand: "New Balance",
    price: 11999,
    originalPrice: 13999,
    discount: "14% off",
    rating: 4.9,
    reviews: 4900,
    sales: "15k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80",
    description: "80s pro-basketball retro classic crafted with premium leather upper and non-marking rubber cupsole."
  },
  {
    title: "Reebok Classic Leather Unisex Sneakers",
    category: "shoes",
    brand: "Reebok",
    price: 6999,
    originalPrice: 7999,
    discount: "12% off",
    rating: 4.7,
    reviews: 5200,
    sales: "16k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80",
    description: "Soft garment leather upper featuring die-cut EVA midsole and high-abrasion rubber outsole for grip."
  },

  // --- EMERGING & BUDGET BRANDS ---
  {
    title: "Comet Apollo Low-Top Retro Sneakers",
    category: "shoes",
    brand: "Comet",
    price: 4299,
    originalPrice: 4999,
    discount: "14% off",
    rating: 4.8,
    reviews: 1890,
    sales: "8k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80",
    description: "Independent homegrown sneaker design with dual-tone paneling, memory foam footbed, and street flair."
  },
  {
    title: "Campus Men's Oxyfit Running Shoes",
    category: "shoes",
    brand: "Campus",
    price: 1499,
    originalPrice: 1999,
    discount: "25% off",
    rating: 4.5,
    reviews: 11200,
    sales: "30k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    description: "Breathable knitted mesh upper with Phylon sole for ultralight cushioning during morning jogs."
  },
  {
    title: "Sparx Sporty Mesh Training Shoes",
    category: "shoes",
    brand: "Sparx",
    price: 1299,
    originalPrice: 1699,
    discount: "23% off",
    rating: 4.6,
    reviews: 14500,
    sales: "35k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
    description: "Heavy-duty outdoor athletic shoes with flexible traction sole and reinforced toe cap protection."
  },

  // --- MEN'S CASUALS, BOOTS & SLIP-ONS ---
  {
    title: "Red Chief Genuine Leather Ankle Boots",
    category: "shoes",
    brand: "Red Chief",
    price: 4995,
    originalPrice: 5995,
    discount: "16% off",
    rating: 4.8,
    reviews: 6400,
    sales: "14k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&q=80",
    description: "Rugged oiled real leather boots built with anti-skid rubber lug sole for extreme durability."
  },
  {
    title: "Woodland Men's Leather Trekking Shoes",
    category: "shoes",
    brand: "Woodland",
    price: 5495,
    originalPrice: 6495,
    discount: "15% off",
    rating: 4.9,
    reviews: 9800,
    sales: "20k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?w=800&q=80",
    description: "Heavy-duty nubuck leather outdoor hiking shoes with reinforced heel bumper and deep tread patterns."
  },
  {
    title: "Crocs Classic Unisex Clogs Black",
    category: "shoes",
    brand: "Crocs",
    price: 2995,
    originalPrice: 3495,
    discount: "14% off",
    rating: 4.8,
    reviews: 24500,
    sales: "50k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80",
    description: "Lightweight water-friendly Croslite foam clogs featuring ventilation ports and pivoting heel strap."
  },
  {
    title: "Bata Men's Leather Formal Slip-On Shoes",
    category: "shoes",
    brand: "Bata",
    price: 2499,
    originalPrice: 2999,
    discount: "16% off",
    rating: 4.6,
    reviews: 8900,
    sales: "22k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800&q=80",
    description: "Sleek formal slip-on loafers crafted from polished leather with cushioned footbed for office wear."
  },
  {
    title: "Sparx Men's Waterproof Flip Flops (Chappal)",
    category: "shoes",
    brand: "Sparx",
    price: 499,
    originalPrice: 649,
    discount: "23% off",
    rating: 4.7,
    reviews: 31000,
    sales: "80k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=800&q=80",
    description: "Durable rubber strap daily wear chappal engineered with anti-slip textured footbed."
  },

  // --- WOMEN'S FOOTWEAR (HEELS, SANDALS, WEDGES) ---
  {
    title: "Zara Patent Leather Stiletto Heels",
    category: "shoes",
    brand: "Zara",
    price: 4990,
    originalPrice: 5990,
    discount: "16% off",
    rating: 4.7,
    reviews: 1650,
    sales: "5k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80",
    description: "Pointed toe high heel pumps featuring sleek 4-inch stiletto design and glossy black finish."
  },
  {
    title: "Jimmy Choo Crystal Embellished Party Heels",
    category: "shoes",
    brand: "Jimmy Choo",
    price: 54900,
    originalPrice: 59900,
    discount: "8% off",
    rating: 4.9,
    reviews: 820,
    sales: "2k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80",
    description: "Luxurious handcrafted Italian satin pumps encrusted with sparkling Swarovski crystal detailing."
  },
  {
    title: "Metro Women's Embroidered Ethnic Chappals",
    category: "shoes",
    brand: "Metro",
    price: 1990,
    originalPrice: 2490,
    discount: "20% off",
    rating: 4.7,
    reviews: 4200,
    sales: "12k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=800&q=80",
    description: "Traditional Kolhapuri style flats decorated with intricate zari embroidery and padded sole."
  },
  {
    title: "Bata Comfit Soft Cushioned Women's Sandals",
    category: "shoes",
    brand: "Bata",
    price: 1699,
    originalPrice: 1999,
    discount: "15% off",
    rating: 4.8,
    reviews: 6800,
    sales: "18k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1562273138-f46be4ebdf33?w=800&q=80",
    description: "Ergonomic arch-support sandals designed with memory foam footbed for pain-free daily walking."
  },
  {
    title: "Crocs Women's Brooklyn Low Wedge Sandals",
    category: "shoes",
    brand: "Crocs",
    price: 4995,
    originalPrice: 5995,
    discount: "16% off",
    rating: 4.8,
    reviews: 3900,
    sales: "10k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1562273138-f46be4ebdf33?w=800&q=80",
    description: "Stylish platform wedge heel featuring LiteRide foam footbed technology for featherlight height."
  },
  {
    title: "H&M Ankle Strap Block Heels",
    category: "shoes",
    brand: "H&M",
    price: 2499,
    originalPrice: 2999,
    discount: "16% off",
    rating: 4.6,
    reviews: 2700,
    sales: "9k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80",
    description: "Chic square toe block heels with adjustable buckled ankle strap for sturdy evening wear."
  },

  // --- ADDITIONAL FOOTWEAR VARIETIES TO TOTAL 50+ ---
  {
    title: "Nike Air Max 90 OG Infrared Sneakers",
    category: "shoes",
    brand: "Nike",
    price: 11995,
    originalPrice: 13995,
    discount: "14% off",
    rating: 4.9,
    reviews: 5800,
    sales: "19k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    description: "Waffle outsole, stitched overlays, and classic TPU accents stay true to the 90s running root."
  },
  {
    title: "Adidas Originals Gazelle Suede Sneakers",
    category: "shoes",
    brand: "Adidas",
    price: 9999,
    originalPrice: 11999,
    discount: "16% off",
    rating: 4.8,
    reviews: 4100,
    sales: "14k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80",
    description: "1991 Gazelle reissue crafted in rich buttery suede with white 3-Stripes and T-toe overlay."
  },
  {
    title: "Puma Future Rider Play On Sneakers",
    category: "shoes",
    brand: "Puma",
    price: 6999,
    originalPrice: 7999,
    discount: "12% off",
    rating: 4.7,
    reviews: 3200,
    sales: "11k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80",
    description: "Lightweight shock-absorbing Federbein outsole combined with vibrant color-blocked upper."
  },
  {
    title: "New Balance 327 Retro Runner Shoes",
    category: "shoes",
    brand: "New Balance",
    price: 9999,
    originalPrice: 11999,
    discount: "16% off",
    rating: 4.8,
    reviews: 3800,
    sales: "13k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80",
    description: "70s heritage wedge silhouette featuring oversized 'N' branding and trail-inspired lug outsole."
  },
  {
    title: "Reebok Club C 85 Vintage Tennis Shoes",
    category: "shoes",
    brand: "Reebok",
    price: 7999,
    originalPrice: 8999,
    discount: "11% off",
    rating: 4.8,
    reviews: 2900,
    sales: "10k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80",
    description: "Clean off-white leather tennis shoes styled with retro woven window box logo."
  },
  {
    title: "Comet X-Ray High-Top Street Sneakers",
    category: "shoes",
    brand: "Comet",
    price: 4799,
    originalPrice: 5499,
    discount: "12% off",
    rating: 4.7,
    reviews: 1420,
    sales: "6k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&q=80",
    description: "High-top canvas and leather paneling designed for ultimate street skating durability."
  },
  {
    title: "Campus Men's North Running Shoes",
    category: "shoes",
    brand: "Campus",
    price: 1799,
    originalPrice: 2299,
    discount: "21% off",
    rating: 4.6,
    reviews: 8400,
    sales: "25k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    description: "Air capsule sole unit provides springy cushioning across long distance walks."
  },
  {
    title: "Sparx Men's Outdoor Sports Sandals",
    category: "shoes",
    brand: "Sparx",
    price: 1199,
    originalPrice: 1499,
    discount: "20% off",
    rating: 4.7,
    reviews: 16800,
    sales: "45k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1562273138-f46be4ebdf33?w=800&q=80",
    description: "Adjustable velcro strap sandals with rugged rubber sole for monsoon and trekking."
  },
  {
    title: "Red Chief Genuine Leather Loafers",
    category: "shoes",
    brand: "Red Chief",
    price: 3995,
    originalPrice: 4795,
    discount: "16% off",
    rating: 4.8,
    reviews: 4100,
    sales: "11k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800&q=80",
    description: "Hand-stitched genuine leather casual slip-on shoes with flexible latex footbed."
  },
  {
    title: "Woodland Men's Canvas Casual Sneakers",
    category: "shoes",
    brand: "Woodland",
    price: 3495,
    originalPrice: 4195,
    discount: "16% off",
    rating: 4.7,
    reviews: 3200,
    sales: "9k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80",
    description: "Heavyweight cotton canvas upper with vulcanized rubber sole for everyday adventure."
  },
  {
    title: "Crocs Offroad Sport Clogs Camo",
    category: "shoes",
    brand: "Crocs",
    price: 3995,
    originalPrice: 4495,
    discount: "11% off",
    rating: 4.8,
    reviews: 6200,
    sales: "15k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80",
    description: "Rugged lugged outsole with adjustable turbo strap for off-road outdoor terrain."
  },
  {
    title: "Bata Ambassador Men's Oxford Shoes",
    category: "shoes",
    brand: "Bata",
    price: 2999,
    originalPrice: 3599,
    discount: "16% off",
    rating: 4.7,
    reviews: 4800,
    sales: "14k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800&q=80",
    description: "Classic lace-up oxford formal shoes crafted from premium polished burnished leather."
  },
  {
    title: "Metro Women's Leather Wedge Sandals",
    category: "shoes",
    brand: "Metro",
    price: 2490,
    originalPrice: 2990,
    discount: "16% off",
    rating: 4.7,
    reviews: 3100,
    sales: "8k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1562273138-f46be4ebdf33?w=800&q=80",
    description: "Comfortable cork wedge heel sandals with metallic strap detailing for festive wear."
  },
  {
    title: "Zara Strappy Metallic Party Sandals",
    category: "shoes",
    brand: "Zara",
    price: 3990,
    originalPrice: 4990,
    discount: "20% off",
    rating: 4.6,
    reviews: 1450,
    sales: "4k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80",
    description: "Delicate metallic gold criss-cross straps over slender 3.5-inch heels."
  },
  {
    title: "H&M Women's Chunky Platform Sneakers",
    category: "shoes",
    brand: "H&M",
    price: 2999,
    originalPrice: 3599,
    discount: "16% off",
    rating: 4.6,
    reviews: 2900,
    sales: "10k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&q=80",
    description: "Chunky 2-inch platform sole sneakers with faux leather & mesh paneling."
  },
  {
    title: "Nike Dunk Low Retro White Black (Panda)",
    category: "shoes",
    brand: "Nike",
    price: 11895,
    originalPrice: 13995,
    discount: "15% off",
    rating: 4.9,
    reviews: 18400,
    sales: "50k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80",
    description: "The street icon panda colorway featuring crisp leather overlays and padded low collar."
  },
  {
    title: "Adidas NMD_R1 Primeblue Sneakers",
    category: "shoes",
    brand: "Adidas",
    price: 12999,
    originalPrice: 14999,
    discount: "13% off",
    rating: 4.8,
    reviews: 5100,
    sales: "16k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80",
    description: "Streamlined sock-like fit with signature midsole plugs and Parley Ocean Plastic knit."
  },
  {
    title: "Puma Suede Classic XXI Red/White",
    category: "shoes",
    brand: "Puma",
    price: 6499,
    originalPrice: 7499,
    discount: "13% off",
    rating: 4.7,
    reviews: 4200,
    sales: "13k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80",
    description: "Full red suede upper with white Puma formstrip and gold foil brand callout."
  },
  {
    title: "Bata Comfit Doctor Extra Soft Slippers",
    category: "shoes",
    brand: "Bata",
    price: 999,
    originalPrice: 1299,
    discount: "23% off",
    rating: 4.8,
    reviews: 12400,
    sales: "35k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=800&q=80",
    description: "Orthopedic doctor extra soft cushion bed designed to relieve plantar heel pain."
  },
  {
    title: "Sparx Canvas Slip-On Casual Shoes",
    category: "shoes",
    brand: "Sparx",
    price: 999,
    originalPrice: 1299,
    discount: "23% off",
    rating: 4.6,
    reviews: 9800,
    sales: "28k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80",
    description: "Easy slip-on design with elastic goring and flexible rubber sole for college."
  },
  {
    title: "Metro Women's Block Heel Pumps",
    category: "shoes",
    brand: "Metro",
    price: 2990,
    originalPrice: 3490,
    discount: "14% off",
    rating: 4.7,
    reviews: 2100,
    sales: "7k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80",
    description: "Comfortable 2.5-inch block heel closed toe pumps suitable for office and evening."
  },
  {
    title: "Red Chief Genuine Leather Casual Sneakers",
    category: "shoes",
    brand: "Red Chief",
    price: 3495,
    originalPrice: 4295,
    discount: "18% off",
    rating: 4.8,
    reviews: 3900,
    sales: "10k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&q=80",
    description: "Genuine tan leather sneakers built with flexible TPU outsole for high traction."
  },
  {
    title: "Woodland Waterproof Leather Hiking Boots",
    category: "shoes",
    brand: "Woodland",
    price: 6495,
    originalPrice: 7495,
    discount: "13% off",
    rating: 4.9,
    reviews: 5400,
    sales: "14k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?w=800&q=80",
    description: "Seam-sealed waterproof thick leather boots with rustproof metal lace hardware."
  },
  {
    title: "Crocs Bayaband Clogs Navy",
    category: "shoes",
    brand: "Crocs",
    price: 3495,
    originalPrice: 3995,
    discount: "12% off",
    rating: 4.8,
    reviews: 11500,
    sales: "30k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80",
    description: "Sporty athletic stripe band around mid-sole with iconic Croslite foam comfort."
  },
  {
    title: "Jimmy Choo Glitter Strappy Sandals",
    category: "shoes",
    brand: "Jimmy Choo",
    price: 49900,
    originalPrice: 54900,
    discount: "9% off",
    rating: 4.9,
    reviews: 640,
    sales: "1k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80",
    description: "Fine champagne glitter fabric sandals with delicate crossover ankle straps."
  },
  {
    title: "Zara Men's Suede Leather Loafers",
    category: "shoes",
    brand: "Zara",
    price: 4990,
    originalPrice: 5990,
    discount: "16% off",
    rating: 4.7,
    reviews: 1890,
    sales: "6k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800&q=80",
    description: "Soft unlined suede driving loafers with penny strap detail and pebbled rubber sole."
  },
  {
    title: "Campus Men's First Running Shoes",
    category: "shoes",
    brand: "Campus",
    price: 1899,
    originalPrice: 2399,
    discount: "20% off",
    rating: 4.6,
    reviews: 7400,
    sales: "22k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    description: "Dual-density springy sole unit providing maximum shock absorption on concrete."
  },
  {
    title: "Reebok Zig Kinetica 3 Running Shoes",
    category: "shoes",
    brand: "Reebok",
    price: 9999,
    originalPrice: 11999,
    discount: "16% off",
    rating: 4.8,
    reviews: 2100,
    sales: "7k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80",
    description: "Zig Energy Bands outsole stretches & snaps back to return energy with every stride."
  },
  {
    title: "Nike Metcon 9 Training Shoes",
    category: "shoes",
    brand: "Nike",
    price: 13995,
    originalPrice: 15995,
    discount: "12% off",
    rating: 4.9,
    reviews: 3100,
    sales: "11k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    description: "Larger Hyperlift plate in heel and rubber rope wrap built for heavy lifting & CrossFit."
  },
  {
    title: "Adidas Terrex AX4 Waterproof Hiking Shoes",
    category: "shoes",
    brand: "Adidas",
    price: 10999,
    originalPrice: 12999,
    discount: "15% off",
    rating: 4.8,
    reviews: 2400,
    sales: "8k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?w=800&q=80",
    description: "Multisport trail shoe featuring GORE-TEX waterproof lining and Continental Rubber outsole."
  }
];

async function injectShoeProducts() {
  try {
    console.log('Connecting to database...');
    await sequelize.authenticate();

    console.log(`Injecting ${shoeProducts.length} footwear items into SQLite database (preserving existing data)...`);
    const saved = await Product.bulkCreate(shoeProducts);

    console.log(`Successfully injected 50+ Premium Sneakers, Boots, Heels, and Chappals into the E-Bazaar database!`);
    process.exit(0);
  } catch (error) {
    console.error('Error injecting footwear products:', error.message);
    process.exit(1);
  }
}

injectShoeProducts();
