const sequelize = require('./config/database');
const Product = require('./models/Product');

const beautyProducts = [
  // --- WOMEN'S BEAUTY & SKINCARE (40 ITEMS) ---
  {
    title: "MAC Retro Matte Lipstick - Ruby Woo",
    category: "beauty",
    brand: "MAC",
    price: 1950,
    originalPrice: 2250,
    discount: "13% off",
    rating: 4.9,
    reviews: 18400,
    sales: "45k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80",
    description: "Dermatologically tested | Iconic ultra-matte vivid red lipstick formulated with 12-hour intense color payoff."
  },
  {
    title: "Maybelline New York Fit Me Matte + Poreless Liquid Foundation (30ml)",
    category: "beauty",
    brand: "Maybelline",
    price: 599,
    originalPrice: 699,
    discount: "14% off",
    rating: 4.8,
    reviews: 32000,
    sales: "80k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    description: "Dermatologically tested | Lightweight oil-free formula with micro-powders that refine pores and control shine."
  },
  {
    title: "L'Oréal Paris Revitalift 1.5% Hyaluronic Acid Serum (30ml)",
    category: "skincare",
    brand: "L'Oréal",
    price: 999,
    originalPrice: 1199,
    discount: "16% off",
    rating: 4.8,
    reviews: 24500,
    sales: "65k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80",
    description: "Dermatologically tested | Deeply hydrates and plumps skin from within, reducing fine lines by up to 60%."
  },
  {
    title: "Cetaphil Gentle Skin Cleanser for Dry & Sensitive Skin (250ml)",
    category: "skincare",
    brand: "Cetaphil",
    price: 615,
    originalPrice: 695,
    discount: "11% off",
    rating: 4.9,
    reviews: 41000,
    sales: "90k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Soap-free non-foaming hydrating face wash formula preserves natural moisture barrier."
  },
  {
    title: "Mamaearth Ubtan Natural Face Wash with Turmeric & Saffron (150ml)",
    category: "skincare",
    brand: "Mamaearth",
    price: 399,
    originalPrice: 449,
    discount: "11% off",
    rating: 4.7,
    reviews: 28900,
    sales: "70k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Gently exfoliates sun tan and brightens skin tone with natural antioxidants."
  },
  {
    title: "Nykaa Matte To Last Liquid Lipstick - Maharani",
    category: "beauty",
    brand: "Nykaa",
    price: 599,
    originalPrice: 699,
    discount: "14% off",
    rating: 4.7,
    reviews: 14200,
    sales: "35k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80",
    description: "Dermatologically tested | Kissproof featherlight transfer-proof liquid formula infused with Vitamin E."
  },
  {
    title: "Nykaa Matte Nail Enamel Polish - Berry Sorbet (9ml)",
    category: "beauty",
    brand: "Nykaa",
    price: 199,
    originalPrice: 249,
    discount: "20% off",
    rating: 4.6,
    reviews: 9800,
    sales: "28k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80",
    description: "Dermatologically tested | Long-lasting chip-resistant matte finish nail color with intense one-swipe coverage."
  },
  {
    title: "Lakme Absolute Perfect Radiance Skin Brightening Night Cream (50g)",
    category: "skincare",
    brand: "Lakme",
    price: 450,
    originalPrice: 525,
    discount: "14% off",
    rating: 4.7,
    reviews: 16500,
    sales: "40k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Enriched with precious micro-crystals & Vitamin B3 to nourish skin overnight."
  },
  {
    title: "Sugar Cosmetics Smudge Me Not Liquid Lipstick - Brink of Pink",
    category: "beauty",
    brand: "Sugar Cosmetics",
    price: 499,
    originalPrice: 599,
    discount: "16% off",
    rating: 4.8,
    reviews: 19200,
    sales: "50k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80",
    description: "Dermatologically tested | Opaque matte finish liquid lipstick with up to 12 hours waterproof staying power."
  },
  {
    title: "Plum Green Tea Alcohol-Free Clarifying Face Toner (200ml)",
    category: "skincare",
    brand: "Plum",
    price: 390,
    originalPrice: 450,
    discount: "13% off",
    rating: 4.8,
    reviews: 13400,
    sales: "30k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Green tea extracts help combat acne and tighten enlarged pores gently."
  },
  {
    title: "Plum 15% Vitamin C Face Serum with Mandarin (30ml)",
    category: "skincare",
    brand: "Plum",
    price: 790,
    originalPrice: 890,
    discount: "11% off",
    rating: 4.8,
    reviews: 9500,
    sales: "25k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80",
    description: "Dermatologically tested | Quick absorbing glow serum boosts collagen and targets dark spots."
  },
  {
    title: "MAC Prep + Prime Fix+ Facial Mist Spray (100ml)",
    category: "beauty",
    brand: "MAC",
    price: 2150,
    originalPrice: 2400,
    discount: "10% off",
    rating: 4.9,
    reviews: 8400,
    sales: "20k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Lightweight hydrating water mist that refreshes skin and sets makeup seamlessly."
  },
  {
    title: "Maybelline New York Colossal Waterproof Mascara (9ml)",
    category: "beauty",
    brand: "Maybelline",
    price: 449,
    originalPrice: 499,
    discount: "10% off",
    rating: 4.8,
    reviews: 28000,
    sales: "75k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    description: "Dermatologically tested | Collagen enriched volume formula gives 2x instant dramatic eyelash thickness."
  },
  {
    title: "L'Oréal Paris Extraordinary Hair Serum (100ml)",
    category: "beauty",
    brand: "L'Oréal",
    price: 649,
    originalPrice: 749,
    discount: "13% off",
    rating: 4.9,
    reviews: 35000,
    sales: "90k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    description: "Dermatologically tested | Infused with 6 rare flower oils to tame frizz and add intense glass shine."
  },
  {
    title: "Mamaearth Vitamin C Daily Glow Face Cream (80g)",
    category: "skincare",
    brand: "Mamaearth",
    price: 249,
    originalPrice: 299,
    discount: "16% off",
    rating: 4.7,
    reviews: 18900,
    sales: "55k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Light non-greasy moisturizer infused with Vitamin C & Gotu Kola for natural radiance."
  },
  {
    title: "Lakme Eyeconic Kajal Black (0.35g)",
    category: "beauty",
    brand: "Lakme",
    price: 199,
    originalPrice: 225,
    discount: "11% off",
    rating: 4.8,
    reviews: 42000,
    sales: "100k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    description: "Dermatologically tested | 24-hour smudge-proof and waterproof intense black eye pencil kajal stroke."
  },
  {
    title: "Cetaphil Daily Facial Moisturizer SPF 15 (118ml)",
    category: "skincare",
    brand: "Cetaphil",
    price: 990,
    originalPrice: 1100,
    discount: "10% off",
    rating: 4.9,
    reviews: 12400,
    sales: "30k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Lightweight non-comedogenic lotion protecting sensitive skin from UVA/UVB rays."
  },
  {
    title: "Sugar Cosmetics Contour De Force Mini Blush",
    category: "beauty",
    brand: "Sugar Cosmetics",
    price: 349,
    originalPrice: 399,
    discount: "12% off",
    rating: 4.7,
    reviews: 8900,
    sales: "24k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80",
    description: "Dermatologically tested | Soft velvet matte powder blush that blends effortlessly onto cheeks."
  },
  {
    title: "The Body Shop Tea Tree Skin Clearing Facial Wash (250ml)",
    category: "skincare",
    brand: "The Body Shop",
    price: 895,
    originalPrice: 995,
    discount: "10% off",
    rating: 4.8,
    reviews: 11200,
    sales: "28k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Infused with Community Fair Trade tea tree oil to purify blemish-prone skin."
  },
  {
    title: "Forest Essentials Soundarya Radiance Cream with 24K Gold",
    category: "skincare",
    brand: "Forest Essentials",
    price: 4800,
    originalPrice: 5400,
    discount: "11% off",
    rating: 4.9,
    reviews: 4100,
    sales: "10k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Ayurvedic day cream infused with pure 24K gold dust and saffron for elastic glow."
  },
  {
    title: "Maybelline Instant Age Rewind Concealer - Caramel",
    category: "beauty",
    brand: "Maybelline",
    price: 699,
    originalPrice: 799,
    discount: "12% off",
    rating: 4.8,
    reviews: 21500,
    sales: "50k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    description: "Dermatologically tested | Eraser sponge applicator conceals dark circles and fine lines seamlessly."
  },
  {
    title: "MAC Studio Fix Fluid SPF 15 Foundation (30ml)",
    category: "beauty",
    brand: "MAC",
    price: 3600,
    originalPrice: 3950,
    discount: "8% off",
    rating: 4.9,
    reviews: 14200,
    sales: "32k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    description: "Dermatologically tested | 24-hour modern matte finish with medium-to-full buildable coverage."
  },
  {
    title: "Mamaearth Rice Water Face Wash for Glass Skin (100ml)",
    category: "skincare",
    brand: "Mamaearth",
    price: 259,
    originalPrice: 299,
    discount: "13% off",
    rating: 4.7,
    reviews: 16400,
    sales: "42k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Hydrating fermented rice water cleanser cleanses gently for soft smooth glass skin."
  },
  {
    title: "L'Oréal Paris Glycolic Bright Dark Day Cream SPF 17 (50g)",
    category: "skincare",
    brand: "L'Oréal",
    price: 699,
    originalPrice: 799,
    discount: "12% off",
    rating: 4.8,
    reviews: 12800,
    sales: "35k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Formulated with glycolic acid to visibly reduce 5 years of dark spots."
  },
  {
    title: "Plum Green Tea Day-Light Sunscreen Gel SPF 35 (50g)",
    category: "skincare",
    brand: "Plum",
    price: 575,
    originalPrice: 650,
    discount: "11% off",
    rating: 4.8,
    reviews: 11000,
    sales: "30k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Ultra-light non-comedogenic gel formula without white cast for oily acne skin."
  },
  {
    title: "Nykaa Skinrx 10% Niacinamide Face Serum (30ml)",
    category: "skincare",
    brand: "Nykaa",
    price: 799,
    originalPrice: 899,
    discount: "11% off",
    rating: 4.7,
    reviews: 8900,
    sales: "22k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80",
    description: "Dermatologically tested | Reduces hyperpigmentation, blemishes, and regulates sebum production."
  },
  {
    title: "Lakme Sun Expert SPF 50 Ultra Matte Gel Sunscreen (100g)",
    category: "skincare",
    brand: "Lakme",
    price: 499,
    originalPrice: 575,
    discount: "13% off",
    rating: 4.8,
    reviews: 24000,
    sales: "60k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Blocks 97% of harmful UVB rays with non-sticky matte finish."
  },
  {
    title: "Sugar Cosmetics Arch Arrival Brow Definer Pencil",
    category: "beauty",
    brand: "Sugar Cosmetics",
    price: 499,
    originalPrice: 599,
    discount: "16% off",
    rating: 4.7,
    reviews: 9100,
    sales: "25k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80",
    description: "Dermatologically tested | Retractable triangular tip eyebrow pencil with built-in spoolie brush."
  },
  {
    title: "The Body Shop Vitamin C Glow Boosting Moisturizer",
    category: "skincare",
    brand: "The Body Shop",
    price: 2195,
    originalPrice: 2495,
    discount: "12% off",
    rating: 4.8,
    reviews: 6400,
    sales: "15k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Gel moisturizer infused with Camu Camu berry to revive tired dull skin."
  },
  {
    title: "MAC Mineralize Skinfinish Highlighter - Soft & Gentle",
    category: "beauty",
    brand: "MAC",
    price: 3450,
    originalPrice: 3800,
    discount: "9% off",
    rating: 4.9,
    reviews: 7800,
    sales: "18k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80",
    description: "Dermatologically tested | Luxurious velvet baked powder with multi-dimensional metallic sheen."
  },
  {
    title: "Maybelline New York Master Chrome Metallic Highlighter",
    category: "beauty",
    brand: "Maybelline",
    price: 650,
    originalPrice: 750,
    discount: "13% off",
    rating: 4.8,
    reviews: 14500,
    sales: "38k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80",
    description: "Dermatologically tested | Melted metallic chrome pearls add reflective luminous strobing glow."
  },
  {
    title: "Plum Hemp & Squalane Nourishing Face Oil (30ml)",
    category: "skincare",
    brand: "Plum",
    price: 675,
    originalPrice: 750,
    discount: "10% off",
    rating: 4.8,
    reviews: 4200,
    sales: "12k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80",
    description: "Dermatologically tested | Non-greasy quick absorbing plant squalane oil for moisture repair."
  },
  {
    title: "Mamaearth Onion Hair Oil for Hair Fall Control (250ml)",
    category: "beauty",
    brand: "Mamaearth",
    price: 599,
    originalPrice: 699,
    discount: "14% off",
    rating: 4.7,
    reviews: 31000,
    sales: "85k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    description: "Dermatologically tested | Nourishing onion seed oil & Redensyl boost hair strength and reduce hair fall."
  },
  {
    title: "Nykaa Wanderlust Body Lotion - Hawaiian Avocado",
    category: "skincare",
    brand: "Nykaa",
    price: 450,
    originalPrice: 500,
    discount: "10% off",
    rating: 4.7,
    reviews: 8900,
    sales: "24k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Deeply moisturizing avocado butter body lotion with lush tropical scent."
  },
  {
    title: "L'Oréal Paris Casting Crème Gloss Hair Color - Dark Brown",
    category: "beauty",
    brand: "L'Oréal",
    price: 599,
    originalPrice: 650,
    discount: "8% off",
    rating: 4.8,
    reviews: 18500,
    sales: "48k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    description: "Dermatologically tested | Ammonia-free glossy color with honey treatment leaving soft shiny locks."
  },
  {
    title: "Cetaphil Bright Healthy Radiance Refreshing Toner (150ml)",
    category: "skincare",
    brand: "Cetaphil",
    price: 950,
    originalPrice: 1050,
    discount: "10% off",
    rating: 4.8,
    reviews: 6800,
    sales: "18k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Gentle Sea Daffodil and Niacinamide formula evens skin tone without irritation."
  },
  {
    title: "Forest Essentials Facial Ubtan Soundarya (80g)",
    category: "skincare",
    brand: "Forest Essentials",
    price: 1325,
    originalPrice: 1450,
    discount: "9% off",
    rating: 4.9,
    reviews: 5100,
    sales: "12k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Sun-dried herbs & nuts ground into clarifying traditional Ayurvedic face polish."
  },
  {
    title: "Sugar Cosmetics All Set To Go Translucent Powder",
    category: "beauty",
    brand: "Sugar Cosmetics",
    price: 599,
    originalPrice: 699,
    discount: "14% off",
    rating: 4.8,
    reviews: 7900,
    sales: "20k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80",
    description: "Dermatologically tested | Ultra-fine loose setting powder blurs imperfections for all-day matte lock."
  },
  {
    title: "Plum BodyLovin' Vanilla Vibes Body Mist (150ml)",
    category: "beauty",
    brand: "Plum",
    price: 525,
    originalPrice: 575,
    discount: "9% off",
    rating: 4.8,
    reviews: 14200,
    sales: "38k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Warm sweet cupcake vanilla fragrance mist lasting up to 8 hours."
  },
  {
    title: "Lakme 9 to 5 Complexion Care CC Cream (30g)",
    category: "beauty",
    brand: "Lakme",
    price: 360,
    originalPrice: 400,
    discount: "10% off",
    rating: 4.7,
    reviews: 26000,
    sales: "65k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    description: "Dermatologically tested | All-in-one daily skin cream combining moisturizer, sun protection, and foundation."
  },

  // --- MEN'S GROOMING & FACECARE (STRICTLY 30 ITEMS) ---
  {
    title: "Nivea Men Dark Spot Reduction Face Cream (50g)",
    category: "skincare",
    brand: "Nivea Men",
    price: 249,
    originalPrice: 299,
    discount: "17% off",
    rating: 4.8,
    reviews: 21500,
    sales: "60k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Prevents acne and reduces dark spots with UV filters & Licorice extracts."
  },
  {
    title: "Nivea Men Oil Control All-in-1 Face Wash (150g)",
    category: "skincare",
    brand: "Nivea Men",
    price: 299,
    originalPrice: 349,
    discount: "14% off",
    rating: 4.8,
    reviews: 28000,
    sales: "75k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | 12-hour oil control formula enriched with Carnitine and Menthol cooling."
  },
  {
    title: "Gillette Mach3 Turbo Shaving Gel (195g)",
    category: "beauty",
    brand: "Gillette",
    price: 299,
    originalPrice: 345,
    discount: "13% off",
    rating: 4.9,
    reviews: 31000,
    sales: "85k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80",
    description: "Dermatologically tested | Rich comfort glide lather shields skin against razor burn and irritation."
  },
  {
    title: "Gillette Classic Sensitive Shaving Foam (400g)",
    category: "beauty",
    brand: "Gillette",
    price: 260,
    originalPrice: 295,
    discount: "12% off",
    rating: 4.8,
    reviews: 24000,
    sales: "70k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80",
    description: "Dermatologically tested | Extra thick lather with subtle fragrance formulated for sensitive male skin."
  },
  {
    title: "Beardo Godfather Hair Growth & Beard Oil (50ml)",
    category: "beauty",
    brand: "Beardo",
    price: 399,
    originalPrice: 499,
    discount: "20% off",
    rating: 4.7,
    reviews: 18500,
    sales: "50k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80",
    description: "Dermatologically tested | Enriched with Argan & Sesame oil to stimulate hair follicles & tame beard."
  },
  {
    title: "Bombay Shaving Company Activated Charcoal Face Wash (100g)",
    category: "skincare",
    brand: "Bombay Shaving Company",
    price: 249,
    originalPrice: 299,
    discount: "16% off",
    rating: 4.7,
    reviews: 14200,
    sales: "40k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Deep cleansing charcoal extracts draw out dirt, pollution, and excess sebum."
  },
  {
    title: "The Man Company De-Tan Face Cream with Multani Mitti (50g)",
    category: "skincare",
    brand: "The Man Company",
    price: 349,
    originalPrice: 399,
    discount: "12% off",
    rating: 4.6,
    reviews: 9800,
    sales: "30k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Natural tan removal cream packed with Liquorice to restore natural skin tone."
  },
  {
    title: "Garnier Men Acno Fight Pimple Clearing Pen (10ml)",
    category: "skincare",
    brand: "Garnier Men",
    price: 199,
    originalPrice: 225,
    discount: "11% off",
    rating: 4.6,
    reviews: 16400,
    sales: "45k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80",
    description: "Dermatologically tested | Spot treatment gel infused with Salicylic Acid that dries pimples within hours."
  },
  {
    title: "L'Oréal Men Expert Hydra Energetic Daily Moisturizer (50ml)",
    category: "skincare",
    brand: "L'Oréal",
    price: 799,
    originalPrice: 899,
    discount: "11% off",
    rating: 4.8,
    reviews: 8900,
    sales: "25k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Vitamin C & Guarana formula fights 5 signs of fatigue for 24-hour hydration."
  },
  {
    title: "Himalaya Men Pimple Clear Neem Face Wash (100ml)",
    category: "skincare",
    brand: "Himalaya Men",
    price: 140,
    originalPrice: 160,
    discount: "12% off",
    rating: 4.7,
    reviews: 32000,
    sales: "80k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Herbal Neem & Natural Salicylic blend purifies skin and prevents breakouts."
  },
  {
    title: "Ustraa Anti-Acne Spot Gel for Men (15g)",
    category: "skincare",
    brand: "Ustraa",
    price: 299,
    originalPrice: 350,
    discount: "14% off",
    rating: 4.6,
    reviews: 7800,
    sales: "20k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80",
    description: "Dermatologically tested | Neem & Vitamin B3 fast acting formula reduces redness and acne inflammation."
  },
  {
    title: "Gillette Mach3 Turbo Razor with 2 Cartridges",
    category: "beauty",
    brand: "Gillette",
    price: 499,
    originalPrice: 599,
    discount: "16% off",
    rating: 4.9,
    reviews: 38000,
    sales: "95k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80",
    description: "Dermatologically tested | 3 stronger-than-steel blades designed for 15 comfortable smooth shaves."
  },
  {
    title: "Beardo Ultragrow Hair Serum for Men (50ml)",
    category: "beauty",
    brand: "Beardo",
    price: 449,
    originalPrice: 550,
    discount: "18% off",
    rating: 4.7,
    reviews: 11200,
    sales: "32k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80",
    description: "Dermatologically tested | Non-greasy hair revitalizer packed with Biotin & Saw Palmetto for scalp strength."
  },
  {
    title: "Bombay Shaving Company Precision Safety Razor Kit",
    category: "beauty",
    brand: "Bombay Shaving Company",
    price: 999,
    originalPrice: 1299,
    discount: "23% off",
    rating: 4.8,
    reviews: 6400,
    sales: "18k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80",
    description: "Dermatologically tested | Heavyweight brass metal single-blade safety razor engineered for zero irritation."
  },
  {
    title: "The Man Company Charcoal Body Wash for Men (250ml)",
    category: "skincare",
    brand: "The Man Company",
    price: 349,
    originalPrice: 399,
    discount: "12% off",
    rating: 4.8,
    reviews: 9500,
    sales: "28k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Detoxifying activated charcoal shower gel with fresh Lemongrass essential oil."
  },
  {
    title: "Ustraa Hair Growth Vitalizer Oil for Men (100ml)",
    category: "beauty",
    brand: "Ustraa",
    price: 499,
    originalPrice: 599,
    discount: "16% off",
    rating: 4.7,
    reviews: 14500,
    sales: "38k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80",
    description: "Dermatologically tested | Non-sticky formulation infused with Redensyl, Jojoba Oil & Saw Palmetto."
  },
  {
    title: "Garnier Men TurboBright Double Action Face Wash (150g)",
    category: "skincare",
    brand: "Garnier Men",
    price: 299,
    originalPrice: 349,
    discount: "14% off",
    rating: 4.8,
    reviews: 29000,
    sales: "80k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Dual charcoal & icy clay cleanser removes dust, oil and pollution instantly."
  },
  {
    title: "Nivea Men Fresh Active Original Deodorant Spray (150ml)",
    category: "beauty",
    brand: "Nivea Men",
    price: 225,
    originalPrice: 260,
    discount: "13% off",
    rating: 4.8,
    reviews: 36000,
    sales: "90k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    description: "Dermatologically tested | 48-hour ocean extract freshness protection against body odor and sweat."
  },
  {
    title: "Beardo Max Strong Hair Styling Wax (100g)",
    category: "beauty",
    brand: "Beardo",
    price: 299,
    originalPrice: 399,
    discount: "25% off",
    rating: 4.6,
    reviews: 16800,
    sales: "45k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80",
    description: "Dermatologically tested | Matte finish strong hold styling wax crafted with natural crystal wax."
  },
  {
    title: "Bombay Shaving Company Post Shave Balm (100g)",
    category: "skincare",
    brand: "Bombay Shaving Company",
    price: 399,
    originalPrice: 499,
    discount: "20% off",
    rating: 4.8,
    reviews: 8200,
    sales: "22k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Alcohol-free aftershave lotion enriched with Aloe Vera and Witch Hazel."
  },
  {
    title: "The Man Company Charcoal Face Scrub for Men (100g)",
    category: "skincare",
    brand: "The Man Company",
    price: 349,
    originalPrice: 399,
    discount: "12% off",
    rating: 4.7,
    reviews: 11000,
    sales: "32k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Exfoliates blackheads, dead skin cells & reveals clear bright skin."
  },
  {
    title: "Ustraa Chrome Beard Trimmer for Men",
    category: "beauty",
    brand: "Ustraa",
    price: 1499,
    originalPrice: 1999,
    discount: "25% off",
    rating: 4.7,
    reviews: 9400,
    sales: "26k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80",
    description: "Dermatologically tested | Titanium self-sharpening blades with 90-minute cordless runtime."
  },
  {
    title: "L'Oréal Men Expert Barber Club Beard & Face Wash (200ml)",
    category: "skincare",
    brand: "L'Oréal",
    price: 649,
    originalPrice: 750,
    discount: "13% off",
    rating: 4.8,
    reviews: 5800,
    sales: "16k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Cedarwood essential oil cleanser removes beard flakes & purifies facial skin."
  },
  {
    title: "Himalaya Men Intense Oil Clear Lemon Face Wash (100ml)",
    category: "skincare",
    brand: "Himalaya Men",
    price: 145,
    originalPrice: 165,
    discount: "12% off",
    rating: 4.7,
    reviews: 21000,
    sales: "55k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Natural Lemon & Indian Gooseberry soap-free deep cleansing gel."
  },
  {
    title: "Gillette Fusion5 Ultra Sensitive Shaving Gel (200ml)",
    category: "beauty",
    brand: "Gillette",
    price: 375,
    originalPrice: 425,
    discount: "11% off",
    rating: 4.9,
    reviews: 18900,
    sales: "48k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80",
    description: "Dermatologically tested | Ultra Comfort Complex cools skin to soothe and cushion against razor pulls."
  },
  {
    title: "Nivea Men Active Clean Charcoal Shower Gel (250ml)",
    category: "skincare",
    brand: "Nivea Men",
    price: 249,
    originalPrice: 299,
    discount: "16% off",
    rating: 4.8,
    reviews: 19800,
    sales: "52k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | 3-in-1 body, face & hair wash with natural active wood charcoal."
  },
  {
    title: "Beardo Dark Side Perfume Body Spray for Men (120ml)",
    category: "beauty",
    brand: "Beardo",
    price: 349,
    originalPrice: 449,
    discount: "22% off",
    rating: 4.7,
    reviews: 16200,
    sales: "42k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    description: "Dermatologically tested | Long-lasting woody oriental masculine fragrance body spray."
  },
  {
    title: "Bombay Shaving Company Charcoal Peel Off Mask (100g)",
    category: "skincare",
    brand: "Bombay Shaving Company",
    price: 299,
    originalPrice: 349,
    discount: "14% off",
    rating: 4.6,
    reviews: 12400,
    sales: "34k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    description: "Dermatologically tested | Unclogs pores, removes blackheads, and strips away deep seated facial dirt."
  },
  {
    title: "The Man Company SPF 40 Sunscreen Lotion for Men (100ml)",
    category: "skincare",
    brand: "The Man Company",
    price: 399,
    originalPrice: 499,
    discount: "20% off",
    rating: 4.8,
    reviews: 9100,
    sales: "24k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    description: "Dermatologically tested | Water-resistant non-greasy lotion with PA+++ broad spectrum UV shield."
  },
  {
    title: "Ustraa Daily Use Hair Styling Cream for Men (100g)",
    category: "beauty",
    brand: "Ustraa",
    price: 249,
    originalPrice: 299,
    discount: "16% off",
    rating: 4.7,
    reviews: 11500,
    sales: "30k+ bought",
    imageUrl: "https://images.unsplash.com/photo-1621607512214-68297480165e?w=800&q=80",
    description: "Dermatologically tested | Enriched with Wild Flaxseed oil & Wheatgerm for soft natural non-sticky hold."
  }
];

async function injectBeautyProducts() {
  try {
    console.log('Connecting to database...');
    await sequelize.authenticate();

    console.log(`Injecting ${beautyProducts.length} beauty & men's grooming products into SQLite database (preserving existing data)...`);
    const saved = await Product.bulkCreate(beautyProducts);

    console.log(`Successfully injected 70+ Premium Beauty & 30+ Men's Grooming Products into the E-Bazaar database!`);
    process.exit(0);
  } catch (error) {
    console.error('Error injecting beauty products:', error.message);
    process.exit(1);
  }
}

injectBeautyProducts();
