require('dotenv').config();
const sequelize = require('./config/database');
const Product = require('./models/Product');

const products = [
  // ── ELECTRONICS ──────────────────────────────────────────────────────────────
  {
    category: 'electronics',
    brand: 'Apple',
    title: 'Apple MacBook Pro 14" M3 Pro',
    price: 199900,
    originalPrice: 219900,
    discount: '9%',
    rating: 4.9,
    reviews: 8432,
    sales: '5k+ sold',
    badge: 'hot',
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=85',
    description: 'Powered by the blazing-fast M3 Pro chip with a 12-core CPU and 18-core GPU. Features a stunning 14-inch Liquid Retina XDR display with ProMotion 120Hz technology.',
  },
  {
    category: 'electronics',
    brand: 'Apple',
    title: 'Apple iPhone 15 Pro Max 256GB',
    price: 159900,
    originalPrice: 169900,
    discount: '6%',
    rating: 4.8,
    reviews: 22150,
    sales: '20k+ sold',
    badge: 'hot',
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=85',
    description: 'Titanium design meets the A17 Pro chip — the most powerful chip ever in a smartphone. Features a 48MP main camera system with 5x Tetraprism optical zoom.',
  },
  {
    category: 'electronics',
    brand: 'Samsung',
    title: 'Samsung Galaxy S24 Ultra 512GB',
    price: 134999,
    originalPrice: 149999,
    discount: '10%',
    rating: 4.7,
    reviews: 14280,
    sales: '10k+ sold',
    badge: 'sale',
    imageUrl: 'https://images.unsplash.com/photo-1707227986523-a38daf1e6019?w=600&q=85',
    description: 'The first Galaxy AI smartphone with an integrated S Pen and a 200MP ProVisual Camera System. Titanium frame with an IP68 rating for extreme durability.',
  },
  {
    category: 'electronics',
    brand: 'Sony',
    title: 'Sony Bravia 65" OLED 4K TV (XR-65A95L)',
    price: 349990,
    originalPrice: 399990,
    discount: '13%',
    rating: 4.8,
    reviews: 3120,
    sales: '2k+ sold',
    badge: 'sale',
    imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&q=85',
    description: 'QD-OLED panel delivers infinitely deep blacks and brilliantly vibrant colors powered by Cognitive Processor XR. Google TV platform with built-in Netflix, Prime, and Apple TV+.',
  },
  {
    category: 'electronics',
    brand: 'Dell',
    title: 'Dell XPS 15 9530 OLED Laptop',
    price: 189990,
    originalPrice: 209990,
    discount: '10%',
    rating: 4.7,
    reviews: 5640,
    sales: '3k+ sold',
    badge: 'new',
    imageUrl: 'https://images.unsplash.com/photo-1544731612-de7f96afe55f?w=600&q=85',
    description: 'Intel Core i9-13900H meets a stunning 3.5K OLED touch display at 120Hz. Engineered for creators with NVIDIA GeForce RTX 4070 graphics and up to 64GB DDR5 RAM.',
  },
  {
    category: 'electronics',
    brand: 'LG',
    title: 'LG 27" UltraFine 4K IPS Monitor (27UQ850-W)',
    price: 59990,
    originalPrice: 74990,
    discount: '20%',
    rating: 4.6,
    reviews: 4890,
    sales: '5k+ sold',
    badge: 'sale',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=85',
    description: 'USB-C 96W charging hub and Thunderbolt 4 connectivity make this monitor the ultimate productivity powerhouse. Certified VESA DisplayHDR 600 with DCI-P3 98% color gamut.',
  },
  {
    category: 'electronics',
    brand: 'Samsung',
    title: 'Samsung 55" QLED 4K Smart TV (QN55Q80C)',
    price: 89990,
    originalPrice: 109990,
    discount: '18%',
    rating: 4.6,
    reviews: 7810,
    sales: '7k+ sold',
    badge: 'sale',
    imageUrl: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=600&q=85',
    description: 'Quantum Dot technology produces over a billion shades of color for breathtaking realism. Neo Quantum Processor 4K with Object Tracking Sound for cinematic audio.',
  },
  // ── GADGETS ──────────────────────────────────────────────────────────────────
  {
    category: 'gadgets',
    brand: 'Sony',
    title: 'Sony WH-1000XM5 Wireless Headphones',
    price: 28990,
    originalPrice: 34990,
    discount: '17%',
    rating: 4.9,
    reviews: 31240,
    sales: '30k+ sold',
    badge: 'hot',
    imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=85',
    description: 'Industry-leading noise cancellation with 8 microphones powered by two processors for the clearest calls ever. 30-hour battery life with a 3-minute quick charge for 3 hours of playback.',
  },
  {
    category: 'gadgets',
    brand: 'Apple',
    title: 'Apple AirPods Pro 2nd Generation',
    price: 24900,
    originalPrice: 26900,
    discount: '7%',
    rating: 4.8,
    reviews: 45100,
    sales: '50k+ sold',
    badge: 'hot',
    imageUrl: 'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=600&q=85',
    description: 'Up to 2x more Active Noise Cancellation with Adaptive Transparency that filters harsh environmental sounds. Precision-crafted H2 chip enables Personalized Spatial Audio with dynamic head tracking.',
  },
  {
    category: 'gadgets',
    brand: 'Apple',
    title: 'Apple Watch Series 9 (GPS, 45mm)',
    price: 45900,
    originalPrice: 49900,
    discount: '8%',
    rating: 4.8,
    reviews: 19870,
    sales: '15k+ sold',
    badge: 'new',
    imageUrl: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=85',
    description: 'The new S9 chip makes Siri on Apple Watch faster and smarter than ever with on-device processing. Double Tap gesture lets you control Apple Watch without touching the screen.',
  },
  {
    category: 'gadgets',
    brand: 'GoPro',
    title: 'GoPro HERO12 Black Action Camera',
    price: 39500,
    originalPrice: 44500,
    discount: '11%',
    rating: 4.7,
    reviews: 8920,
    sales: '5k+ sold',
    badge: 'new',
    imageUrl: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=600&q=85',
    description: 'Captures 5.3K60 ultra-HD video and 27MP photos with the legendary HyperSmooth 6.0 stabilization. 100% waterproof to 10m with an all-new Enduro battery for 50% longer shoots.',
  },
  {
    category: 'gadgets',
    brand: 'Intel',
    title: 'Intel Core i9-13900K Desktop Processor',
    price: 54999,
    originalPrice: 62999,
    discount: '13%',
    rating: 4.8,
    reviews: 6230,
    sales: '4k+ sold',
    badge: 'hot',
    imageUrl: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600&q=85',
    description: '24-core hybrid architecture (8P + 16E) delivering record-breaking single and multi-threaded performance. Unlocked for overclocking with Intel Turbo Boost Max Technology 3.0.',
  },
  {
    category: 'gadgets',
    brand: 'Samsung',
    title: 'Samsung Galaxy Watch 6 Classic (47mm)',
    price: 34999,
    originalPrice: 39999,
    discount: '13%',
    rating: 4.6,
    reviews: 11240,
    sales: '8k+ sold',
    badge: 'new',
    imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=85',
    description: 'The iconic rotating bezel returns with a 13% larger display and the most comprehensive health tracking on Galaxy. Advanced sleep coaching, body composition, and ECG monitoring.',
  },
  // ── FASHION ──────────────────────────────────────────────────────────────────
  {
    category: 'fashion',
    brand: "Levi's",
    title: "Levi's 511 Slim Fit Stretch Jeans",
    price: 2999,
    originalPrice: 3999,
    discount: '25%',
    rating: 4.5,
    reviews: 28900,
    sales: '50k+ sold',
    badge: 'sale',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=85',
    description: "Cut close through the hip and thigh with a slim leg opening, these stretch jeans move with you all day. Levi's iconic craftsmanship with advanced stretch denim technology.",
  },
  {
    category: 'fashion',
    brand: 'Zara',
    title: 'Zara Oversized Blazer with Lapels',
    price: 5490,
    originalPrice: 6990,
    discount: '21%',
    rating: 4.4,
    reviews: 7120,
    sales: '10k+ sold',
    badge: 'new',
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4417?w=600&q=85',
    description: 'Impeccably tailored oversized blazer in premium Italian fabric with wide notched lapels. A versatile wardrobe hero that transitions effortlessly from boardroom to evening.',
  },
  {
    category: 'fashion',
    brand: 'Nike',
    title: 'Nike Sportswear Club Fleece Hoodie',
    price: 3495,
    originalPrice: 4395,
    discount: '20%',
    rating: 4.7,
    reviews: 62300,
    sales: '100k+ sold',
    badge: 'hot',
    imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=85',
    description: 'Brushed-back fleece construction locks in warmth with a soft, comfortable feel. An iconic silhouette with a Swoosh logo that has become the definitive streetwear statement.',
  },
  {
    category: 'fashion',
    brand: 'Calvin Klein',
    title: 'Calvin Klein Cotton Stretch Trunk 3-Pack',
    price: 2499,
    originalPrice: 3499,
    discount: '29%',
    rating: 4.6,
    reviews: 38700,
    sales: '80k+ sold',
    badge: 'sale',
    imageUrl: 'https://images.unsplash.com/photo-1527719327859-c6ce80353573?w=600&q=85',
    description: 'Premium cotton-modal blend with four-way stretch engineered for all-day comfort and support. Iconic CK waistband in a modern contour pouch design.',
  },
  {
    category: 'fashion',
    brand: 'H&M',
    title: 'H&M Slim Fit Chino Pants',
    price: 1799,
    originalPrice: 2499,
    discount: '28%',
    rating: 4.3,
    reviews: 15400,
    sales: '20k+ sold',
    badge: 'sale',
    imageUrl: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=85',
    description: 'Slim-fit chinos in a soft, stretchy twill fabric that keeps you sharp throughout the day. Five-pocket design with a flat front and zip fly for a clean, modern silhouette.',
  },
  {
    category: 'fashion',
    brand: 'FabIndia',
    title: 'FabIndia Pure Silk Handwoven Saree',
    price: 8990,
    originalPrice: 11990,
    discount: '25%',
    rating: 4.7,
    reviews: 4560,
    sales: '5k+ sold',
    badge: 'new',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=85',
    description: 'Hand-woven by master artisans from Varanasi using 100% pure Kanjivaram silk with a zari border. Each saree is a unique piece of living heritage, carrying centuries of Indian weaving tradition.',
  },
  // ── SHOES ─────────────────────────────────────────────────────────────────────
  {
    category: 'shoes',
    brand: 'Nike',
    title: 'Nike Air Jordan 1 Retro High OG',
    price: 11999,
    originalPrice: 13999,
    discount: '14%',
    rating: 4.9,
    reviews: 52800,
    sales: '40k+ sold',
    badge: 'hot',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=85',
    description: 'The shoe that changed basketball forever, now reissued in premium leather with the original colorblocking. Michael Jordan wore these in 1985, and the icon lives on in every stitch.',
  },
  {
    category: 'shoes',
    brand: 'Adidas',
    title: 'Adidas Ultraboost 23 Running Shoes',
    price: 17999,
    originalPrice: 21999,
    discount: '18%',
    rating: 4.8,
    reviews: 29150,
    sales: '25k+ sold',
    badge: 'sale',
    imageUrl: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=85',
    description: 'BOOST midsole delivers unmatched energy return with every stride, powered by 20% more boost than its predecessor. Primeknit+ upper adapts to your foot like a second skin.',
  },
  {
    category: 'shoes',
    brand: 'Puma',
    title: 'Puma RS-X3 Puzzle Sneakers',
    price: 6499,
    originalPrice: 8999,
    discount: '28%',
    rating: 4.5,
    reviews: 14200,
    sales: '15k+ sold',
    badge: 'sale',
    imageUrl: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&q=85',
    description: "Retro-futuristic RS-X silhouette with exaggerated midsole and mixed textures from Puma's archives. RS (Running System) technology cushioning for all-day street-ready comfort.",
  },
  {
    category: 'shoes',
    brand: 'New Balance',
    title: 'New Balance 990v6 Made in USA',
    price: 22999,
    originalPrice: 24999,
    discount: '8%',
    rating: 4.8,
    reviews: 9870,
    sales: '5k+ sold',
    badge: 'new',
    imageUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=85',
    description: 'Handcrafted in the USA with premium pigskin and mesh upper delivering unparalleled quality. ENCAP midsole combines a polyurethane rim with an EVA core for ultimate support.',
  },
  // ── GROCERIES ─────────────────────────────────────────────────────────────────
  {
    category: 'groceries',
    brand: 'Amul',
    title: 'Amul Gold Full Cream Milk 1L (Pack of 6)',
    price: 420,
    originalPrice: 444,
    discount: '5%',
    rating: 4.7,
    reviews: 85600,
    sales: '200k+ sold',
    badge: null,
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=85',
    description: 'Rich and creamy full-fat milk standardised to 6% fat from India\'s most trusted dairy cooperative. Processed under hygienic conditions with extended shelf life and zero preservatives.',
  },
  {
    category: 'groceries',
    brand: 'Tata',
    title: 'Tata Sampann Organic Dal Combo (3kg)',
    price: 599,
    originalPrice: 750,
    discount: '20%',
    rating: 4.6,
    reviews: 32100,
    sales: '50k+ sold',
    badge: 'sale',
    imageUrl: 'https://images.unsplash.com/photo-1585478259715-876ace5aff97?w=600&q=85',
    description: 'Certified organic dal sourced directly from Indian farmers, retaining natural proteins and fiber. Includes 1kg each of Chana Dal, Moong Dal, and Masoor Dal in resealable packs.',
  },
  {
    category: 'groceries',
    brand: 'Nestle',
    title: "Nescafé Gold Blend Coffee 200g",
    price: 649,
    originalPrice: 799,
    discount: '19%',
    rating: 4.6,
    reviews: 41200,
    sales: '60k+ sold',
    badge: 'sale',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=85',
    description: 'A rich and full-bodied blend of finely roasted Arabica and Robusta beans for a premium café experience at home. The iconic gold standard of instant coffee in a distinctive jar.',
  },
  {
    category: 'groceries',
    brand: 'Britannia',
    title: 'Britannia NutriChoice 5 Grain Biscuits 750g',
    price: 165,
    originalPrice: 200,
    discount: '18%',
    rating: 4.4,
    reviews: 58900,
    sales: '100k+ sold',
    badge: null,
    imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=85',
    description: 'Baked with 5 health grains — oats, corn, ragi, wheat, and barley — for a guilt-free snacking experience. High-fiber formula that keeps you full longer, with no maida and no added colors.',
  },
];

async function seed() {
  try {
    console.log('[Seeder] Connecting to database...');
    await sequelize.authenticate();
    console.log('[Seeder] Connection established.');

    console.log('[Seeder] Dropping and recreating tables...');
    await sequelize.sync({ force: true });
    console.log('[Seeder] Tables recreated.');

    console.log(`[Seeder] Inserting ${products.length} products...`);
    await Product.bulkCreate(products, { validate: true });

    console.log(`\n✅  [Seeder] Successfully seeded ${products.length} products into the database!`);
    console.log('[Seeder] Categories seeded: electronics, gadgets, fashion, shoes, groceries');
  } catch (err) {
    console.error('\n❌  [Seeder] Seeding failed:', err.message);
    process.exit(1);
  } finally {
    await sequelize.close();
    process.exit(0);
  }
}

seed();
