require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_ANON_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('[Seeder Error] SUPABASE_URL or SUPABASE_ANON_KEY/SUPABASE_SERVICE_ROLE_KEY is missing from .env');
  console.error('Please configure them before running the script.');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const products = [
  {
    title: 'Amul Premium Gold Pasteurized Butter',
    description: 'Amul salted butter made from pure milk fat. A classic addition to breakfast toasts, baking, and gourmet cooking.',
    price: 275.00,
    originalPrice: 290.00,
    discount: '5% OFF',
    rating: 4.9,
    reviews: 1420,
    sales: '10k+ bought',
    badge: 'Best Seller',
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&auto=format&fit=crop&q=80',
    category: 'groceries',
    brand: 'Amul',
    stock: 250,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Nestlé EVERYDAY Dairy Whitener',
    description: 'Perfect tea and coffee companion. Rich, smooth, and creamy milk powder that dissolves instantly to make delicious cups.',
    price: 430.00,
    originalPrice: 460.00,
    discount: '6% OFF',
    rating: 4.7,
    reviews: 850,
    sales: '5k+ bought',
    badge: 'Popular',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
    category: 'groceries',
    brand: 'Nestlé',
    stock: 180,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Britannia Good Day Cashew Cookies',
    description: 'Crunchy cookies loaded with rich cashews and butter. Perfect companion for your daily tea time.',
    price: 120.00,
    originalPrice: 140.00,
    discount: '14% OFF',
    rating: 4.8,
    reviews: 2100,
    sales: '15k+ bought',
    badge: 'Tea Time Special',
    imageUrl: 'https://images.unsplash.com/photo-1558961309-dbdf71799f5a?w=600&auto=format&fit=crop&q=80',
    category: 'groceries',
    brand: 'Britannia',
    stock: 400,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Apple iPhone 15 Pro (128GB, Natural Titanium)',
    description: 'Features a strong and light aerospace-grade titanium design, an advanced 48MP main camera, and the industry-defining A17 Pro chip.',
    price: 127990.00,
    originalPrice: 134900.00,
    discount: '5% OFF',
    rating: 4.9,
    reviews: 340,
    sales: '100+ bought',
    badge: 'Flagship',
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80',
    category: 'electronics',
    brand: 'Apple',
    stock: 35,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Nothing Phone (2) (256GB, Dark Grey)',
    description: 'Unique glyph interface, transparent back panel design, 50MP dual rear cameras, and Snapdragon 8+ Gen 1 power.',
    price: 39999.00,
    originalPrice: 44999.00,
    discount: '11% OFF',
    rating: 4.6,
    reviews: 210,
    sales: '300+ bought',
    badge: 'Trendsetter',
    imageUrl: 'https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=600&auto=format&fit=crop&q=80',
    category: 'electronics',
    brand: 'Nothing',
    stock: 60,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    description: 'Industry-leading active noise cancellation, exceptional call quality, 30-hour battery life, and ultra-comfortable design.',
    price: 29990.00,
    originalPrice: 34990.00,
    discount: '14% OFF',
    rating: 4.8,
    reviews: 480,
    sales: '500+ bought',
    badge: 'Audiophile Choice',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    category: 'electronics',
    brand: 'Sony',
    stock: 45,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'boAt Airdopes 141 Bluetooth Earbuds',
    description: 'True wireless earbuds with 42H playtime, low latency beast mode for gaming, and ENx tech noise cancellation for calls.',
    price: 1299.00,
    originalPrice: 4490.00,
    discount: '71% OFF',
    rating: 4.3,
    reviews: 3200,
    sales: '10k+ bought',
    badge: 'Super Saver',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
    category: 'gadgets',
    brand: 'boat',
    stock: 500,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'JBL Flip 6 Portable Waterproof Speaker',
    description: 'Powerful signature sound, 2-way speaker system, IP67 dustproof and waterproof, and up to 12 hours of non-stop playtime.',
    price: 9999.00,
    originalPrice: 11999.00,
    discount: '16% OFF',
    rating: 4.7,
    reviews: 1430,
    sales: '2k+ bought',
    badge: 'Outdoor Best',
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80',
    category: 'gadgets',
    brand: 'JBL',
    stock: 120,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Logitech MX Master 3S Wireless Mouse',
    description: 'Ergonomic mouse with 8K DPI track-on-glass sensor, quiet clicks, electromagnetic magspeed scrolling, and custom profiles.',
    price: 9495.00,
    originalPrice: 10995.00,
    discount: '13% OFF',
    rating: 4.8,
    reviews: 890,
    sales: '1k+ bought',
    badge: 'Developer Special',
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
    category: 'gadgets',
    brand: 'Logitech',
    stock: 95,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "Levi's Men's 511 Slim Fit Jeans",
    description: 'Classic slim-fit denim jeans with subtle stretch for comfort. Features signature 5-pocket styling and leather patch.',
    price: 2499.00,
    originalPrice: 4199.00,
    discount: '40% OFF',
    rating: 4.5,
    reviews: 1200,
    sales: '3k+ bought',
    badge: 'Must Have',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&auto=format&fit=crop&q=80',
    category: 'clothing',
    brand: "LEVI'S",
    stock: 150,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Zara Classic Linen Blend Blazer',
    description: 'Premium linen-blend tailored blazer with notched lapels and flap pockets. Lightweight design suitable for summer events.',
    price: 5990.00,
    originalPrice: 7990.00,
    discount: '25% OFF',
    rating: 4.4,
    reviews: 180,
    sales: '200+ bought',
    badge: 'Designer Pick',
    imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop&q=80',
    category: 'clothing',
    brand: 'ZARA',
    stock: 40,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Tommy Hilfiger Signature Crewneck Sweater',
    description: 'Soft cotton crewneck knit sweater with iconic flag embroidery on chest. Perfect layer for winter and cool evening wear.',
    price: 4599.00,
    originalPrice: 6999.00,
    discount: '34% OFF',
    rating: 4.6,
    reviews: 310,
    sales: '500+ bought',
    badge: 'Winter Core',
    imageUrl: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&auto=format&fit=crop&q=80',
    category: 'clothing',
    brand: 'TOMMY HILFIGER',
    stock: 85,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Nike Air Max Excee Running Shoes',
    description: 'Classic mesh and leather runner silhouette inspired by the Air Max 90. Features iconic visible Air sole unit cushioning.',
    price: 6795.00,
    originalPrice: 7995.00,
    discount: '15% OFF',
    rating: 4.7,
    reviews: 960,
    sales: '2k+ bought',
    badge: 'Athlete Choice',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    category: 'shoes',
    brand: 'NIKE',
    stock: 110,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Adidas Originals Stan Smith Sneakers',
    description: 'Timeless white leather tennis shoes with clean design and signature green heel tab. Sustainable Primegreen construction.',
    price: 5599.00,
    originalPrice: 7999.00,
    discount: '30% OFF',
    rating: 4.8,
    reviews: 1420,
    sales: '4k+ bought',
    badge: 'Classic',
    imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop&q=80',
    category: 'shoes',
    brand: 'adidas',
    stock: 140,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Puma Smash v2 Classic Leather Sneakers',
    description: 'Court-inspired classic shoes featuring premium leather upper, clean Puma formstrip logo, and durable rubber cupsole.',
    price: 2199.00,
    originalPrice: 3999.00,
    discount: '45% OFF',
    rating: 4.4,
    reviews: 2100,
    sales: '8k+ bought',
    badge: 'Top Value',
    imageUrl: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&auto=format&fit=crop&q=80',
    category: 'shoes',
    brand: 'PUMA',
    stock: 220,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: "L'Oreal Paris Revitalift Hyaluronic Acid Serum",
    description: 'Intensely hydrating face serum loaded with 1.5% pure Hyaluronic Acid. Instantly plumps and smooths skin, reducing wrinkles.',
    price: 849.00,
    originalPrice: 999.00,
    discount: '15% OFF',
    rating: 4.6,
    reviews: 3400,
    sales: '20k+ bought',
    badge: 'Derma Approved',
    imageUrl: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600&auto=format&fit=crop&q=80',
    category: 'beauty',
    brand: "L'ORÉAL PARIS",
    stock: 300,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Maybelline New York Colossal Waterproof Mascara',
    description: 'Get volume lashes instantly with the colossal waterproof mascara. Infused with collagen to thicken and define lashes.',
    price: 349.00,
    originalPrice: 449.00,
    discount: '22% OFF',
    rating: 4.5,
    reviews: 4800,
    sales: '30k+ bought',
    badge: 'Amazon Choice',
    imageUrl: 'https://images.unsplash.com/photo-1631730359575-38e4755d772b?w=600&auto=format&fit=crop&q=80',
    category: 'beauty',
    brand: 'MAYBELLINE',
    stock: 450,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Cetaphil Gentle Skin Cleanser',
    description: 'Dermatologist recommended daily facial cleanser for dry, sensitive skin. Mild, non-irritating, soap-free formula.',
    price: 325.00,
    originalPrice: 375.00,
    discount: '13% OFF',
    rating: 4.8,
    reviews: 5600,
    sales: '25k+ bought',
    badge: 'Skincare Essential',
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80',
    category: 'beauty',
    brand: 'Cetaphil',
    stock: 400,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Prestige Omega Deluxe Granite Cookware Set',
    description: '3-piece non-stick cookware set including Kadai with glass lid, Tawa, and Fry Pan. Durable granite finish, metal spoon friendly.',
    price: 2890.00,
    originalPrice: 3890.00,
    discount: '25% OFF',
    rating: 4.5,
    reviews: 1420,
    sales: '2k+ bought',
    badge: 'Kitchen Hero',
    imageUrl: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
    category: 'home-kitchen',
    brand: 'Prestige',
    stock: 100,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Milton Thermosteel Duo Deluxe Flask (1L)',
    description: 'Double-wall vacuum insulated hot and cold water bottle. Premium rust-proof steel flask that keeps drinks hot/cold for 24h.',
    price: 990.00,
    originalPrice: 1190.00,
    discount: '16% OFF',
    rating: 4.7,
    reviews: 2100,
    sales: '5k+ bought',
    badge: 'Best Seller',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80',
    category: 'home-kitchen',
    brand: 'MILTON',
    stock: 200,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Borosil Vision Glass Set (6 Pieces)',
    description: 'Elegant visual glass set made of 100% borosilicate glass. Flameproof, microwave-safe, and stays crystal clear over time.',
    price: 495.00,
    originalPrice: 595.00,
    discount: '16% OFF',
    rating: 4.6,
    reviews: 890,
    sales: '3k+ bought',
    badge: 'Housewarming Pick',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    category: 'home-kitchen',
    brand: 'BOROSIL',
    stock: 150,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Yonex Nanoray 18i Light Badminton Racket',
    description: 'Ultra-lightweight (77g) carbon graphite badminton racket. High tension racket suitable for aggressive speed players.',
    price: 1999.00,
    originalPrice: 2999.00,
    discount: '33% OFF',
    rating: 4.7,
    reviews: 1420,
    sales: '4k+ bought',
    badge: 'Tournament Choice',
    imageUrl: 'https://images.unsplash.com/photo-1613918431703-aa49298bb36b?w=600&auto=format&fit=crop&q=80',
    category: 'sports',
    brand: 'YONEX',
    stock: 90,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Nivia Storm Rubber Football (Size 5)',
    description: 'FIFA quality standard sized soccer ball. Made of durable rubber material ideal for hard ground without grass.',
    price: 449.00,
    originalPrice: 549.00,
    discount: '18% OFF',
    rating: 4.4,
    reviews: 980,
    sales: '3k+ bought',
    badge: 'Training Grade',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&auto=format&fit=crop&q=80',
    category: 'sports',
    brand: 'NIVIA',
    stock: 130,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    title: 'Spalding NBA Street Basketball (Size 7)',
    description: 'Official size and weight outdoor rubber basketball. Deep channel grip design for excellent ball handling control.',
    price: 2199.00,
    originalPrice: 2799.00,
    discount: '21% OFF',
    rating: 4.6,
    reviews: 720,
    sales: '1k+ bought',
    badge: 'Street Legend',
    imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&auto=format&fit=crop&q=80',
    category: 'sports',
    brand: 'SPALDING',
    stock: 80,
    gstRate: 18.0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

async function seed() {
  try {
    console.log('[Supabase Seeder] Authenticating and inserting products into Supabase...');
    const { data, error } = await supabase
      .from('products')
      .insert(products);

    if (error) {
      throw error;
    }

    console.log('Successfully seeded products across official brand directories into Supabase!');
  } catch (err) {
    console.error('[Supabase Seeder Error]:', err.message);
  }
}

seed();
