const sequelize = require('../config/database');
const Product = require('../models/Product');

const items = [
  // Today's Deals (isDeal: true)
  {
    title: 'Nothing Phone (2a) Pro - 12GB RAM, 256GB',
    description: 'Experience pure speed with the Nothing Phone (2a) Pro. Features a unique glyph interface, transparent back cover, 12GB RAM, and 256GB storage.',
    price: 54999.00,
    originalPrice: 69999.00,
    discount: '21% OFF',
    rating: 4.7,
    reviews: 182,
    sales: '300+ sold',
    badge: '21% OFF',
    category: 'electronics',
    brand: 'Nothing',
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80',
    stock: 45,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'SonicGlass A1 Transparent Speaker',
    description: 'Crystal-clear acoustic sound meets breathtaking transparency. The SonicGlass A1 features dynamic LED glow beats and premium Bluetooth 5.3 connectivity.',
    price: 39999.00,
    originalPrice: 54500.00,
    discount: '26% OFF',
    rating: 4.6,
    reviews: 95,
    sales: '120+ sold',
    badge: '26% OFF',
    category: 'gadgets',
    brand: 'MorningBlues',
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=80',
    stock: 30,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'ThinkTab X11 Rugged Tablet - 11" 2.5K',
    description: 'A drop-tested, water-resistant rugged tablet built for demanding conditions. 11-inch 2.5K high-contrast display with long battery life.',
    price: 34999.00,
    originalPrice: 42000.00,
    discount: '16% OFF',
    rating: 4.5,
    reviews: 64,
    sales: '80+ sold',
    badge: '16% OFF',
    category: 'electronics',
    brand: 'Lenovo',
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80',
    stock: 50,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Realme P4 Power - 6000mAh Battery',
    description: 'Unmatched stamina with the massive 6000mAh battery. The Realme P4 Power sports 33W dart charging, a fluid 120Hz display, and robust processor.',
    price: 22999.00,
    originalPrice: 28999.00,
    discount: '20% OFF',
    rating: 4.4,
    reviews: 140,
    sales: '250+ sold',
    badge: '20% OFF',
    category: 'electronics',
    brand: 'Realme',
    imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80',
    stock: 80,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Pre-Draped Silk Blend Saree',
    description: 'Stunning pre-draped silk-blend saree for effortless elegance. Designed for high fashion events with modern styling and gold thread detailing.',
    price: 2499.00,
    originalPrice: 5999.00,
    discount: '58% OFF',
    rating: 4.8,
    reviews: 420,
    sales: '1k+ sold',
    badge: '58% OFF',
    category: 'clothing',
    brand: 'Zara',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
    stock: 120,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Eco-conscious Athleisure Co-ord Set',
    description: 'Eco-conscious coordinated sport set with premium breathability. Designed with recycled fabrics offering lightweight moisture absorption.',
    price: 1299.00,
    originalPrice: 2999.00,
    discount: '56% OFF',
    rating: 4.5,
    reviews: 670,
    sales: '4k+ sold',
    badge: '56% OFF',
    category: 'clothing',
    brand: 'H&M',
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80',
    stock: 200,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Soft Tailoring Wide Leg Trousers',
    description: 'Premium casual trousers with soft tailoring and wide legs. Perfect for daily office styling or weekend hangouts.',
    price: 1899.00,
    originalPrice: 3499.00,
    discount: '45% OFF',
    rating: 4.6,
    reviews: 310,
    sales: '2k+ sold',
    badge: '45% OFF',
    category: 'clothing',
    brand: 'Levis',
    imageUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=600&q=80',
    stock: 150,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Air Zoom Pegasus 41',
    description: 'Unmatched comfort for runners. The Air Zoom Pegasus 41 features reactive cushioning pads and breathable engineered mesh upper structures.',
    price: 6499.00,
    originalPrice: 10999.00,
    discount: '40% OFF',
    rating: 4.8,
    reviews: 820,
    sales: '1k+ sold',
    badge: '40% OFF',
    category: 'shoes',
    brand: 'Nike',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
    stock: 90,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Black Spiral Ceramic Vase',
    description: 'Elevate your living space aesthetics with the Vaaree spiral ceramic vase. Features dynamic textures and minimalist black glaze.',
    price: 899.00,
    originalPrice: 2499.00,
    discount: '64% OFF',
    rating: 4.9,
    reviews: 150,
    sales: '600+ sold',
    badge: '64% OFF',
    category: 'home-kitchen',
    brand: 'Vaaree',
    imageUrl: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=600&q=80',
    stock: 110,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Ribbed Cream Planter (Set of 2)',
    description: 'Set of 2 elegant ribbed planters in cream. Made of weather-resistant ceramics, perfect for housing air purifiers, snake plants, or succulents.',
    price: 1199.00,
    originalPrice: 3000.00,
    discount: '60% OFF',
    rating: 4.7,
    reviews: 240,
    sales: '800+ sold',
    badge: '60% OFF',
    category: 'home-kitchen',
    brand: 'Pepperfry',
    imageUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=600&q=80',
    stock: 75,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Minimalist Metal Wall Clock',
    description: 'Sleek metal wall clock with quiet quartz sweep movements. Minimalist tick markers fit seamlessly into modern home decorations.',
    price: 1499.00,
    originalPrice: 3599.00,
    discount: '58% OFF',
    rating: 4.6,
    reviews: 90,
    sales: '400+ sold',
    badge: '58% OFF',
    category: 'home-kitchen',
    brand: 'Urban Ladder',
    imageUrl: 'https://images.unsplash.com/photo-1563861826100-9cb868fdad1c?auto=format&fit=crop&w=600&q=80',
    stock: 65,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Smart Air Purifier Diffuser combo',
    description: 'Breathe clean, fresh air with the integrated HEPA filter and aroma diffuser combo. Smart sensors monitor humidity and PM2.5 levels.',
    price: 8999.00,
    originalPrice: 14999.00,
    discount: '40% OFF',
    rating: 4.8,
    reviews: 320,
    sales: '1k+ sold',
    badge: '40% OFF',
    category: 'home-kitchen',
    brand: 'Philips',
    imageUrl: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?auto=format&fit=crop&w=600&q=80',
    stock: 40,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Apple MacBook Air M3',
    description: 'Supercharged by Apple M3 chip. Thin, lightweight design with up to 18 hours of battery life and liquid retina display.',
    price: 92900.00,
    originalPrice: 114900.00,
    discount: '19% OFF',
    rating: 4.9,
    reviews: 1420,
    sales: '5k+ sold',
    badge: '19% OFF',
    category: 'electronics',
    brand: 'Apple',
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80',
    stock: 30,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Sony Alpha 7 IV Mirrorless Camera',
    description: 'Premium hybrid mirrorless camera featuring a 33MP Exmor R sensor, high-speed autofocus, and advanced 4K 60p recording capabilities.',
    price: 184990.00,
    originalPrice: 219900.00,
    discount: '15% OFF',
    rating: 4.9,
    reviews: 215,
    sales: '100+ sold',
    badge: '15% OFF',
    category: 'electronics',
    brand: 'Sony',
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80',
    stock: 12,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'OnePlus Nord CE4 Lite 5G',
    description: 'Affordable performance powerhouse with a 50MP camera system, 5500mAh high-density battery, and 80W SuperVOOC flash charging.',
    price: 19999.00,
    originalPrice: 22999.00,
    discount: '13% OFF',
    rating: 4.4,
    reviews: 580,
    sales: '4k+ sold',
    badge: '13% OFF',
    category: 'electronics',
    brand: 'OnePlus',
    imageUrl: 'https://images.unsplash.com/photo-1565630916779-e303be97b6f5?auto=format&fit=crop&w=600&q=80',
    stock: 90,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'JBL Tune 770NC Wireless Headphones',
    description: 'Over-ear adaptive noise-cancelling headphones featuring JBL Pure Bass sound and up to 70 hours of non-stop battery life.',
    price: 5499.00,
    originalPrice: 9999.00,
    discount: '45% OFF',
    rating: 4.5,
    reviews: 2400,
    sales: '10k+ sold',
    badge: '45% OFF',
    category: 'gadgets',
    brand: 'JBL',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    stock: 150,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Boult Audio UFO Gaming Earbuds',
    description: 'Futuristic gaming earbuds with custom breathing LED lights, 45ms low latency mode, and high clarity dual microphones.',
    price: 1499.00,
    originalPrice: 4999.00,
    discount: '70% OFF',
    rating: 4.6,
    reviews: 1430,
    sales: '5k+ sold',
    badge: '70% OFF',
    category: 'gadgets',
    brand: 'BOULT AUDIO',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
    stock: 300,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Textured Wool Blend Coat',
    description: 'Sophisticated long coat crafted from a textured wool blend. Styled with side pockets, double breasted front, and notched lapels.',
    price: 8990.00,
    originalPrice: 14990.00,
    discount: '40% OFF',
    rating: 4.7,
    reviews: 88,
    sales: '200+ sold',
    badge: '40% OFF',
    category: 'clothing',
    brand: 'Zara',
    imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80',
    stock: 40,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Puma RS-X Geek Unisex Sneakers',
    description: 'Retro-futuristic style with modern overlays. Featuring comfortable running system padding and traction-rich rubber outer soles.',
    price: 4799.00,
    originalPrice: 7999.00,
    discount: '40% OFF',
    rating: 4.6,
    reviews: 154,
    sales: '1k+ sold',
    badge: '40% OFF',
    category: 'shoes',
    brand: 'Puma',
    imageUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=600&q=80',
    stock: 85,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Decathlon Arpenaz 20L Backpack',
    description: 'Perfect lightweight backpack for day hikes and travel treks. 20-litre capacity with multiple zipped pockets and ergonomic straps.',
    price: 799.00,
    originalPrice: 1299.00,
    discount: '38% OFF',
    rating: 4.5,
    reviews: 950,
    sales: '3k+ sold',
    badge: '38% OFF',
    category: 'sports',
    brand: 'DECATHLON',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    stock: 220,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'Classic Aluminum Pressure Cooker',
    description: 'Reliable and robust pressure cooker with an inside-fitting lid. Made from virgin aluminum, perfect for quick and safe cooking.',
    price: 1899.00,
    originalPrice: 2499.00,
    discount: '24% OFF',
    rating: 4.8,
    reviews: 1980,
    sales: '10k+ sold',
    badge: '24% OFF',
    category: 'home-kitchen',
    brand: 'Hawkins',
    imageUrl: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80',
    stock: 140,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },
  {
    title: 'L-Oreal Paris Revitalift Serum',
    description: 'Intensively hydrating face serum loaded with 1.5% pure Hyaluronic Acid. Instantly plumps skin and reduces fine lines.',
    price: 699.00,
    originalPrice: 999.00,
    discount: '30% OFF',
    rating: 4.7,
    reviews: 3120,
    sales: '15k+ sold',
    badge: '30% OFF',
    category: 'beauty',
    brand: "L'Oreal",
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&q=80',
    stock: 250,
    gstRate: 18.0,
    isDeal: true,
    isNew: false
  },

  // New Arrivals (isNew: true)
  {
    title: 'Air Max 2026 Edition',
    description: 'Next generation air technology. The Nike Air Max 2026 features full-length air tubes for maximum support and a futuristic look.',
    price: 14999.00,
    originalPrice: 16999.00,
    discount: '11% OFF',
    rating: 4.9,
    reviews: 80,
    sales: '100+ bought',
    badge: 'NEW',
    category: 'shoes',
    brand: 'Nike',
    imageUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=600&q=80',
    stock: 25,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Oversized Linen Blend Blazer',
    description: 'A relaxed-fit blazer made with breathable linen blend fabric. Designed with front pockets and elegant tortoise-shell buttons.',
    price: 5999.00,
    originalPrice: 7999.00,
    discount: '25% OFF',
    rating: 4.8,
    reviews: 140,
    sales: '300+ bought',
    badge: 'NEW',
    category: 'clothing',
    brand: 'Zara',
    imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=600&q=80',
    stock: 35,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Textured Knit Polo Shirt',
    description: 'Classic polo collar shirt crafted from premium textured cotton knit. Lightweight and breathable for daily wear.',
    price: 1999.00,
    originalPrice: 2499.00,
    discount: '20% OFF',
    rating: 4.7,
    reviews: 210,
    sales: '500+ bought',
    badge: 'NEW',
    category: 'clothing',
    brand: 'H&M',
    imageUrl: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=600&q=80',
    stock: 120,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Retro High-Top Sneakers - Nebula',
    description: 'Bold retro style with cloud-like comfort. Features high-top designs, colorful suede accents, and non-slip rubber soles.',
    price: 4499.00,
    originalPrice: 5999.00,
    discount: '25% OFF',
    rating: 4.6,
    reviews: 95,
    sales: '200+ bought',
    badge: 'NEW',
    category: 'shoes',
    brand: 'Comet',
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80',
    stock: 45,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Apple Watch Series 11 - 45mm GPS',
    description: 'Stay connected, healthy, and safe. The Apple Watch Series 11 features blood oxygen monitoring, ECG alerts, and a brighter display.',
    price: 44900.00,
    originalPrice: 47900.00,
    discount: '6% OFF',
    rating: 4.9,
    reviews: 140,
    sales: '100+ bought',
    badge: 'NEW',
    category: 'electronics',
    brand: 'Apple',
    imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=600&q=80',
    stock: 30,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Galaxy Z Flip 7 - 512GB',
    description: 'Pocket-sized folding powerhouse. Features a larger cover screen, upgraded cameras, and Snapdragon Gen 4 processors.',
    price: 99999.00,
    originalPrice: 109999.00,
    discount: '9% OFF',
    rating: 4.7,
    reviews: 98,
    sales: '50+ bought',
    badge: 'NEW',
    category: 'electronics',
    brand: 'Samsung',
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80',
    stock: 15,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'WH-1000XM6 Wireless Noise Cancelling',
    description: 'Unrivaled noise cancellation and high-resolution sound quality. Enjoy up to 40 hours of playback on a single charge.',
    price: 32990.00,
    originalPrice: 36990.00,
    discount: '10% OFF',
    rating: 4.8,
    reviews: 120,
    sales: '300+ bought',
    badge: 'NEW',
    category: 'electronics',
    brand: 'Sony',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    stock: 40,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'MX Master 4S Advanced Wireless Mouse',
    description: 'The absolute standard in productivity mice. Features high-precision scroll wheels and a comfortable ergonomic grip.',
    price: 9499.00,
    originalPrice: 10999.00,
    discount: '13% OFF',
    rating: 4.8,
    reviews: 230,
    sales: '800+ bought',
    badge: 'NEW',
    category: 'gadgets',
    brand: 'Logitech',
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80',
    stock: 55,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Samsung Galaxy S24 Ultra - 512GB',
    description: 'Next-level photography with the 200MP lens, integrated S-Pen stylus, Snapdragon 8 Gen 3 speed, and durable titanium structure.',
    price: 129999.00,
    originalPrice: 139999.00,
    discount: '7% OFF',
    rating: 4.9,
    reviews: 1840,
    sales: '1k+ bought',
    badge: 'NEW',
    category: 'electronics',
    brand: 'Samsung',
    imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80',
    stock: 20,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Sony PS5 Slim Console',
    description: 'Slimmer design with 1TB SSD storage, ultra-high speed loading speeds, immersive 3D audio, and real-time ray-tracing support.',
    price: 44990.00,
    originalPrice: 54990.00,
    discount: '18% OFF',
    rating: 4.8,
    reviews: 780,
    sales: '800+ bought',
    badge: 'NEW',
    category: 'electronics',
    brand: 'Sony',
    imageUrl: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=600&q=80',
    stock: 15,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'CMF Phone 1 by Nothing',
    description: 'Highly customizable smartphone with modular accessories, a bright AMOLED screen, MediaTek Dimensity 7300, and clean Nothing OS.',
    price: 15999.00,
    originalPrice: 19999.00,
    discount: '20% OFF',
    rating: 4.6,
    reviews: 310,
    sales: '2k+ bought',
    badge: 'NEW',
    category: 'electronics',
    brand: 'Nothing',
    imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80',
    stock: 80,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Boat Nirvana Space Wireless ANC',
    description: 'Spatial audio headphones with active noise cancellation, custom sound profiles, and massive 100 hours playback capacity.',
    price: 3999.00,
    originalPrice: 7990.00,
    discount: '50% OFF',
    rating: 4.5,
    reviews: 1200,
    sales: '3k+ bought',
    badge: 'NEW',
    category: 'gadgets',
    brand: 'boat',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
    stock: 200,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Logitech MX Keys S Keyboard',
    description: 'Premium backlit wireless keyboard with silent fluid strokes and smart illumination automation.',
    price: 12995.00,
    originalPrice: 14995.00,
    discount: '13% OFF',
    rating: 4.8,
    reviews: 640,
    sales: '1k+ bought',
    badge: 'NEW',
    category: 'gadgets',
    brand: 'Logitech',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    stock: 60,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Adidas Ultraboost Light Running Shoes',
    description: 'The lightest Ultraboost shoe yet, built with responsive light-boost foam capsules and breathable Primeknit mesh wrappers.',
    price: 15999.00,
    originalPrice: 19999.00,
    discount: '20% OFF',
    rating: 4.9,
    reviews: 320,
    sales: '500+ bought',
    badge: 'NEW',
    category: 'shoes',
    brand: 'Adidas',
    imageUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=600&q=80',
    stock: 45,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Reebok Classic Leather Vintage',
    description: 'Classic heritage retro running design. Genuine leather upper with retro colorways and cushioned EVA midsole.',
    price: 5999.00,
    originalPrice: 7999.00,
    discount: '25% OFF',
    rating: 4.7,
    reviews: 180,
    sales: '600+ bought',
    badge: 'NEW',
    category: 'shoes',
    brand: 'Reebok',
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80',
    stock: 70,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Zara Linen Shirt with Pocket',
    description: 'Breathable long-sleeve linen shirt. Styled with front chest pocket, buttoned cuffs, and clean relaxed silhouette.',
    price: 2990.00,
    originalPrice: 3990.00,
    discount: '25% OFF',
    rating: 4.6,
    reviews: 215,
    sales: '1k+ bought',
    badge: 'NEW',
    category: 'clothing',
    brand: 'Zara',
    imageUrl: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=600&q=80',
    stock: 120,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Nykaa Velvet Matte Lipstick',
    description: 'Highly pigmented velvet matte lipstick that lasts up to 12 hours. Enriched with Vitamin E for soft, smooth lips.',
    price: 399.00,
    originalPrice: 499.00,
    discount: '20% OFF',
    rating: 4.5,
    reviews: 890,
    sales: '3k+ bought',
    badge: 'NEW',
    category: 'beauty',
    brand: 'Nykaa',
    imageUrl: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=600&q=80',
    stock: 180,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  },
  {
    title: 'Prestige Multi-Cooker Kettle',
    description: 'Multi-utility electric kettle with variable temperature controls. Perfect for boiling water, milk, eggs, or instant noodles.',
    price: 1499.00,
    originalPrice: 1999.00,
    discount: '25% OFF',
    rating: 4.7,
    reviews: 950,
    sales: '2k+ bought',
    badge: 'NEW',
    category: 'home-kitchen',
    brand: 'Prestige',
    imageUrl: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80',
    stock: 110,
    gstRate: 18.0,
    isDeal: false,
    isNew: true
  }
];

async function seed() {
  try {
    console.log('[Seeder] Syncing schemas...');
    await sequelize.sync({ alter: true });
    
    console.log('[Seeder] Seeding deals and new arrivals products...');
    for (const item of items) {
      const [prod, created] = await Product.findOrCreate({
        where: { title: item.title },
        defaults: item
      });
      if (!created) {
        await prod.update(item);
      }
    }
    console.log('[Seeder] Successfully seeded all 40 deals/new-arrival products!');
    process.exit(0);
  } catch (err) {
    console.error('[Seeder] Failed to seed:', err);
    process.exit(1);
  }
}

seed();
